name: "Control de Practicantes"
description: "Pipeline: Control Practicantes → Silver → Gold con Flags"
version: "1.0.0"

# Configuración global
config:
  log_dir: "logs"
  stop_on_error: true

# Definición de stages
stages:
  - name: "Control Practicantes Bronze → Silver"
    description: "Procesamiento de archivo Excel a Parquet Silver"
    module: "src.modules.control_practicantes.steps.step1_controlpracticantes"
    function: "procesar_sin_gui"
    params:
      # ruta_archivo y carpeta_salida se pasan dinámicamente desde el executor
    outputs:
      - name: "parquet_silver"
        path_template: "${output_dir}/silver/control_practicantes_silver.parquet"
        required: true
      - name: "excel_silver"
        path_template: "${output_dir}/silver/control_practicantes_silver.xlsx"
        required: false
  
  - name: "Control Practicantes Silver → Gold"
    description: "Generación de capa Gold con tiempo de servicio y flags"
    module: "src.modules.control_practicantes.steps.step2_controlpracticantes"
    function: "procesar_sin_gui"
    params:
      # ruta_silver y carpeta_gold se pasan dinámicamente desde el executor
    outputs:
      - name: "parquet_gold"
        path_template: "${output_dir}/gold/control_practicantes_flagsgold.parquet"
        required: true
      - name: "excel_gold"
        path_template: "${output_dir}/gold/control_practicantes_flagsgold.xlsx"
        required: false